version = 0.1

[default.deploy.parameters]
stack_name = "vendor-statements-api"
resolve_s3 = true
s3_prefix = "vendor-statements-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "StageName=\"dev\" BucketName=\"vendor-statements-storage-1ed73d42\""
image_repositories = []
