service: vendor-statements

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10
  region: us-east-1  # Change to your preferred region
  memorySize: 1024
  timeout: 30
  environment:
    FLASK_ENV: production
    # Add your environment variables here
    # AZURE_OAI_ENDPOINT: ${env:AZURE_OAI_ENDPOINT}
    # AZURE_OAI_KEY: ${env:AZURE_OAI_KEY}
    # AZURE_OAI_DEPLOYMENT_NAME: ${env:AZURE_OAI_DEPLOYMENT_NAME}
    # AZURE_OAI_API_VERSION: ${env:AZURE_OAI_API_VERSION}

functions:
  api:
    handler: lambda_function.lambda_handler
    events:
      - httpApi: '*'
    layers:
      - !Ref DependenciesLambdaLayer

layers:
  dependencies:
    name: vendor-statements-dependencies
    description: Dependencies for vendor-statements application
    compatibleRuntimes:
      - python3.10
    path: vendor-statements-layer.zip

package:
  patterns:
    - '!node_modules/**'
    - '!venv/**'
    - '!__pycache__/**'
    - '!tests/**'
    - '!.pytest_cache/**'
    - '!.vscode/**'
    - '!.github/**'
    - '!.git/**'
    - '!*.zip'
    - '!.env*'
    - '!*.sh'
    - '!temp_packages/**'
    - '!lambda_layer/**'
    - '!lambda_package/**'
    - '!uploads/**'
    - '!*.md'
    - '!Dockerfile'
    - '!*.yml'
    - '!*.yaml'
    - 'lambda_function.py'
    - 'app.py'
    - 'azure_openai_client.py'
    - 'chatbot_service.py'
    - 'data_validator.py'
    - 'file_parser.py'
    - 'header_mapper.py'
    - 'pdftocsv.py'
    - 'field_definitions.json'

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    strip: true
